### ISSUE TITLE
About proxy

### ISSUE THREAD

**Issue by andriuspit** [gkbrk/slowloris#14]
I tried using some proxies, but always get "Timeout" exception. Using same proxy with requests module - works. Or if I use with '--https' argument it just hangs, nothing happens.

**Comment by andriuspit** [comment]
1. Using without proxy it works fine.
2. Trying to use it with just proxy, i get following:
> Traceback (most recent call last):
>   File "slowloris.py", line 134, in <module>
>     main()
>   File "slowloris.py", line 108, in main
>     s = init_socket(ip)
>   File "slowloris.py", line 88, in init_socket
>     s.connect((ip, args.port))
>   File "C:\Python27\lib\site-packages\socks.py", line 96, in wrapper
>     return function(*args, **kwargs)
>   File "C:\Python27\lib\site-packages\socks.py", line 817, in connect
>     raise GeneralProxyError("Socket error", error)
> socks.GeneralProxyError: Socket error: timed out

3. Using with "--https" with "proxy" options, it hangs without any output.
*Using just with "--https" option (without proxy), no sockets are created and stops at "recreating sockets" (i guess host have to be on https). Output:
    [09-10-2017 09:01:25] Creating sockets...
    [09-10-2017 09:01:25] Creating socket nr 0
    [09-10-2017 09:01:25] Sending keep-alive headers... Socket count: 0
    [09-10-2017 09:01:25] Recreating socket...

**Comment by gkbrk** [comment]
When using `--https`, are you also giving it a port with `--port`? Can you try just https with a port number? If it's https, it's usually 443.

**Comment by andriuspit** [comment]
I always provide it. But for the --port I used 8080 or 8081 (i assume it for the host port.) My host is not on https. My whole command would look like this:

> slowloris.py [host_ip] -p 8080 -v -x --proxy-host [proxy_ip] --proxy-port [proxy_port] --https

**Comment by gkbrk** [comment]
If the host isn't on https, why are you passing --https as an option? That option isn't for the proxy, it is for the host.
