### ISSUE TITLE
main() not called when used from command line

### ISSUE THREAD

**Issue by NickMRamirez** [gkbrk/slowloris#2]
I am new to python and I was not able to get the slowloris.py script to work until I added `main()` to the bottom. Is this a required step that's missing from the documentation?

I am invoking it as python3 ./slowloris.py 10.0.0.2

**Comment by gkbrk** [comment]
That looks like a bug, definitely not a missing step. Thanks for the report.

@NickMRamirez would you be interested in fixing it? Something like this should work.

```python
if __name__ == "__main__":
    main()
```
