### ISSUE TITLE
macOS Socket Limit 247

### ISSUE THREAD

**Issue by thatsmellything** [gkbrk/slowloris#24]
It seems that the socket count on mac is 247, idk how to fix or if it is a bug. 
![bug](https://user-images.githubusercontent.com/26822428/56223682-71c35e00-602b-11e9-9d96-16862597405e.png)

Also don't worry this is my own website I am testing it on.

**Comment by gkbrk** [comment]
I don't think that's related to you running it on Mac OS. It is most likely a limit by the server you're testing.

**Comment by Avinm** [comment]
@gkbrk : Can confirm that this is a macos limit, I tried the same host on linux and was able to create 2000 sockets, whereas mac allowed only 247.
