### ISSUE TITLE
SyntaxError: EOL while scanning string literal

### ISSUE THREAD

**Issue by iamsajjad** [gkbrk/slowloris#28]
while import slowloris or run .py file raise this error
```
s.send("GET /?{} HTTP/1.1
                             ^
SyntaxError: EOL while scanning string literal
```

**Comment by gkbrk** [comment]
That looks like you only have a partial file. Can you try re-installing or re-downloading?

**Comment by SALKHAFAJI** [comment]
the package install successfully but when i import it raise this error i try it on google colab but it didn't work

**Comment by gkbrk** [comment]
Closing the issue for inactivity. Let me know if there are still problems with the files.
