### ISSUE TITLE
Question about X-a:

### ISSUE THREAD

**Issue by f0lg0** [gkbrk/slowloris#32]
At line 167 you send some data with sockets to keep the connections alive: "X-a: " followed by some random numbers. Is this actually random data or "X-a:" means something? Thank you!

**Comment by gkbrk** [comment]
The header name `X-a` is just a name picked randomly to be short, in order to minimize the needed bandwidth. The format `X-Header-Name` just means the header is an extension and not a regular one.

The random number is actually random data.
