### ISSUE TITLE
Might be fixed for apache

### ISSUE THREAD

**Issue by momadthenomad** [gkbrk/slowloris#33]
I wanted to see if one of my Apache websites is vulnerable and when I ran it, it just keeps saying socket: 0. My Apache configuration uses the event mpm with 50 threads per process and about 12 processes. Either I'm doing it wrong, or I think Apache might've finally fixed the issue. I am using Apache v2.4.41.

Can someone please confirm?

**Comment by f0lg0** [comment]
Yes, Apache has implemented a few modules to stop that. I've also tried to run it against my server,   sockets actually get created and send data but the website still runs flawlessly.
