### ISSUE TITLE
Error in slowloris installation

### ISSUE THREAD

**Issue by FaizanNehal** [gkbrk/slowloris#40]
I am getting a error when trying to install slowloris with the provided pip3 command, the error is provided below, am I missing something here
![Capture](https://user-images.githubusercontent.com/45764507/87859464-a587e480-c94e-11ea-98ed-dcf0f1006adb.PNG)

**Comment by D1g1talHack3r** [comment]
Its better to git clone install it for example once you look for the github slowloris repository copy the link and before pasting the link on your terminal(termux or kali or etc) type git clone then paste the link >

(https://github.com/gkbrk/slowloris)

**Comment by gkbrk** [comment]
@FaizanNehal That looks like a network error from either your system or from PyPI itself. Are you able to install any other packages from pip?

If it doesn't work at all, you can clone the git repo or just download `slowloris.py` from [here](https://raw.githubusercontent.com/gkbrk/slowloris/master/slowloris.py) as it's a single file.

**Comment by aminvakil** [comment]
As @gkbrk has said:

> I can't really recommend people to execute code from arbitrary sources, as I control neither dockerhub nor the aminvakil/slowloris Dockerfile.

in https://github.com/gkbrk/slowloris/pull/34#issuecomment-627601620, he doesn't recommend using docker image which has been made for this repo not by himself. @FaizanNehal but you can still check the contents of https://github.com/aminvakil/slowloris/blob/master/Dockerfile and run
```
docker run --rm aminvakil/slowloris example.com
```
 without using `pip`, in case you're familiar with docker.

**Comment by FaizanNehal** [comment]
@gkbrk I was able to clone the slowloris and run it with git clone command but the problem here is that I have to open the slowloris directory or provide the full path in order to run this tool. Is there a way so that i can only use the command `slowloris` from any directory to run this tool?
