### ISSUE TITLE
can't open file 'slowloris': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by baibhav470** [gkbrk/slowloris#45]
can't open file 'slowloris': [Errno 2] No such file or directory
when i was using HOIC
Please help

`root@kali:~# sudo apt-get update
Hit:1 https://download.mono-project.com/repo/ubuntu vs-bionic InRelease   
Hit:2 http://ftp.harukasan.org/kali kali-rolling InRelease                
Reading package lists... Done
root@kali:~# sudo apt-get install python
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python is already the newest version (2.7.17-2).
0 upgraded, 0 newly installed, 0 to remove and 692 not upgraded.
root@kali:~# git clone https://github.com/gkbrk/slowloris.git
Cloning into 'slowloris'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 106 (delta 2), reused 4 (delta 2), pack-reused 98
Receiving objects: 100% (106/106), 19.53 KiB | 571.00 KiB/s, done.
Resolving deltas: 100% (49/49), done.
root@kali:~# sudo cd slowloris & then type chmod u+x setup.py
-bash: syntax error near unexpected token `then'
root@kali:~# sudo cd slowloris
sudo: cd: command not found
root@kali:~# cd slowloris
root@kali:~/slowloris# chmod u+x setup.py
root@kali:~/slowloris# python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
copying slowloris.py -> build/lib.linux-x86_64-2.7
running install_lib
copying build/lib.linux-x86_64-2.7/slowloris.py -> /usr/local/lib/python2.7/dist-packages
byte-compiling /usr/local/lib/python2.7/dist-packages/slowloris.py to slowloris.pyc
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/Slowloris-0.2.1.egg-info
root@kali:~/slowloris# python slowloris 45.127.101.81
python: can't open file 'slowloris': [Errno 2] No such file or directory
root@kali:~/slowloris#`

**Comment by TheGameFreak720** [comment]
Why not follow the instructions and install with pip3? Since you also have the cloned repo you don't need to install the program. Just need to run it

**Comment by gkbrk** [comment]
After installing it, you can just run `slowloris whatever` instead of `python slowloris whatever`. Or if you are cloning the repo, just run the single file without installing it. Or install with pip.
