### ISSUE TITLE
how do i run it (im new to coding)

### ISSUE THREAD

**Issue by gewoonIguus** [gkbrk/slowloris#50]
i have cloned the code but i dont know how to get it to run. can you please help me? and yes i've read the stuff in your text

**Comment by Marcopy123** [comment]
install python 3 from the official website : [https://www.python.org/downloads/](https://www.python.org/downloads/)
then, go to the folder containing the python code of slowloris.
execute the following code :
`python3 slowloris.py example.com`   change example.com to whatever website (don't execute it on websites that didn't give permission)

**Comment by biggamer1912** [comment]
So how do i execute it 
pls help me as i scammer tried to get my bank details

**Comment by gkbrk** [comment]
Sorry, this is a security testing tool and I'm pretty sure the website you're planning to test it on didn't hire you as a security researcher. If you think those people are doing something illegal, feel free to report them to the relevant authorities.

**Comment by biggamer1912** [comment]
I am running tests on my own website pls help me
