### ISSUE TITLE
amazing but question

### ISSUE THREAD

**Issue by jazxminemasters** [gkbrk/slowloris#58]
hello this is amazing tool but i was just wondering how do you stop the attack, i just turned off the command prompt but is that he proper way to stop the attack?

**Comment by gkbrk** [comment]
You can inspect the output of `ps aux` to see if the script is still running.

Something like `ps aux | grep slowloris` should provide clues.

**Comment by debian-user-france1** [comment]
Well Ctrl-c is simply stopping everything
