### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by rfornear** [gkbrk/slowloris#62]
There is a syntax error or line 108 keeping it from executing

**Comment by gkbrk** [comment]
That line is a simple string formatting, and shouldn't cause a syntax error. Which version of Python are you running Slowloris with? And which operating system are you using for this?

**Comment by jonathanazc** [comment]
I got the syntax error for line 108 and it doesn't execute. I am also using python 2.7.12+ with Kali Linux

**Comment by gkbrk** [comment]
The script needs Python 3. I didn't think anyone still used Python 2.

**Comment by jonathanazc** [comment]
Do you know how to change python version to 3 because I updated it to python 3.5.2+?

**Comment by ajoddo20** [comment]
@jonathanazc Did you find a solution for getting this to run in Kali linux? Or find another working option (I think we are working on the same class assignment)

**Comment by jonathanazc** [comment]
@ajoddo20 no i did not find a solution to run it in kali

**Comment by gkbrk** [comment]
> Ubuntu 16.04 LTS (Xenial Xerus) was released on 21 April 2016.

> Python 3.5.2 was released on June 26th, 2016.

> Python 2.7.12 Release Date: June 25, 2016

Is there a legitimate reason you're running software from almost 6 years ago?

**Comment by Boca-NeedM** [comment]
Raspberry Pi3 and Bullseye (OS) with Python 3.9.2 works perfect..

root@raspberrypi:/home/pi/slowloris# python3 slowloris.py example.com
[05-05-2022 12:58:27] Attacking example.com with 150 sockets.
[05-05-2022 12:58:27] Creating sockets...
[05-05-2022 12:58:41] Sending keep-alive headers... Socket count: 150
[05-05-2022 12:58:56] Sending keep-alive headers... Socket count: 150
^Z
[2]+  Stopped                 python3 slowloris.py example.com
