### ISSUE TITLE
"Namespace" object has no attribute 'ip'

### ISSUE THREAD

**Issue by vanh285** [gkbrk/slowloris#74]
![image](https://user-images.githubusercontent.com/82790548/199283664-4778a835-27c7-4b41-b0bc-98c5ddf13e6d.png)

py -3 --version
Python 3.10.2

**Comment by gkbrk** [comment]
This should be fixed now. Can you check?

**Comment by vanh285** [comment]
Going to try that rn!

**Comment by vanh285** [comment]
Failed to create new socket: [Errno 11001] getaddrinfo failed 

Another issue comes up. Thank you for the quick response.

**Comment by gkbrk** [comment]
You can't call it like `localhost:80`. Need to give port separately. Like `py -3 slowloris.py -p 80 localhost`.

**Comment by vanh285** [comment]
This works! Thank you for you support!
