### ISSUE TITLE
Sockets are not created  

### ISSUE THREAD

**Issue by MiChaelinzo** [gkbrk/slowloris#90]
It always send 0 socket, how can I fix this? I'm testing a website.
<img width="343" alt="Screenshot 2023-06-04 141403" src="https://github.com/gkbrk/slowloris/assets/68110223/41931b16-1b4a-4907-9b94-97ddf2674678">

**Comment by starXultra** [comment]
This happens to me when you put https:// infront of the url
try `slowloris portal.moi.gov.qa`
Also I think you set up to many sockets, the default is 150. IF the above doesn't work reduce the number of sockets and try again.

**Comment by MiChaelinzo** [comment]
Alright, thank you!

**Comment by starXultra** [comment]
If it works, please specify which solution fixed it and mark it as solved
