### ISSUE TITLE
https mode is not working 

### ISSUE THREAD

**Issue by MiChaelinzo** [gkbrk/slowloris#94]
<img width="356" alt="Screenshot 2023-10-14 171422" src="https://github.com/gkbrk/slowloris/assets/68110223/de1d2588-e45f-4e09-8401-fb962984772c">

**Comment by gkbrk** [comment]
Hmm, could you also pass `--port 443`? I think `--https` doesn't set that by default right now.

**Comment by MiChaelinzo** [comment]
<img width="443" alt="1" src="https://github.com/gkbrk/slowloris/assets/68110223/d7e0ced8-c4f6-48f0-ae2f-7f8b98563c9f">

**Comment by gkbrk** [comment]
Looks like a problem with the network, we don't control anything as low-level as the ssl implementation. So from the perspective of the tool it's supposed to be able to connect without configuring anything.

Are you able to connect to that site over https, like with curl or a browser? Also the tool is supposed to work without needing root, so you can try without _sudo_ as well.

Just to have them as a reference, what are the python3 and openssl versions that are installed on this system?

**Comment by MiChaelinzo** [comment]
> Looks like a problem with the network, we don't control anything as low-level as the ssl implementation. So from the perspective of the tool it's supposed to be able to connect without configuring anything.
> 
> Are you able to connect to that site over https, like with curl or a browser? Also the tool is supposed to work without needing root, so you can try without _sudo_ as well.
> 
> Just to have them as a reference, what are the python3 and openssl versions that are installed on this system?

Hello @gkbrk I'm currently using a TOR IP too currently etc. I'm using python version 3.9.2 and openssl 1.1.1w also I tried without root/sudo.

**Comment by MiChaelinzo** [comment]
I tried removing my TOR/Vpn but still the same error, the http works well etc. but https got the errors.

**Comment by MiChaelinzo** [comment]
found the problem I'm in latest openssl version is not compatible maybe downgrading will fix this issue
<img width="356" alt="Screenshot 2023-10-17 133138" src="https://github.com/gkbrk/slowloris/assets/68110223/bb59c28b-c142-4248-8477-459e537e6f25">
